---
- name: nginx
  become: true
  apt:
    name: nginx
    state: latest        
  notify: start nginx
- name : downlaod index.html 
  get_url:
    url: https://s3-us-west-2.amazonaws.com/studentapi-cit/index.html
    dest: /var/www/html/index.html

- name: permissive selinux
  selinux:
    policy: targeted
    state: permissive



