---
- name: nginx
  become: true
  apt:
    name: nginx
    state: latest        
      
- name: start httpd
  become: true
  service:
    name: nginx 
    state: restarted
- name : downlaod index.html 
  get_url:
    src: https://s3-us-west-2.amazonaws.com/studentapi-cit/index.html
    dest: /var/www/html/index.html

