---
- hosts: all
  become: true
  tasks:
    - name: httpd
      apt:
        name: httpd
        state: latest        
      
    - name: start httpd
      service:
        name: httpd 
        state: restarted
    - name : downlaod index.html 
      get_url:
        src: https://s3-us-west-2.amazonaws.com/studentapi-cit/index.html
        dest: /var/www/html/index.html

