---
# tasks file for backend
- name: install java
  package: 
    name: openjdk-11-jdk
    state: latest
- name: extract
  unarchive:
    src: "https://downloads.apache.org/tomcat/tomcat-9/v9.0.85/bin/apache-tomcat-9.0.85.tar.gz"
    dest: /opt/
    remote_src: true

- name: create deamon
  become: true
  copy:
    src: tomcat.service
    dest: /etc/systemd/system/tomcat.service
    mode: 664
  notify: start tomcat

- name: deploy war
  get_url:
    url: https://s3-us-west-2.amazonaws.com/studentapi-cit/student.war
    dest: /opt/apache-tomcat-9.0.85/webapps/