---
# tasks file for backend
- name: downlaod tomcat
  get_url:
    url: https://downloads.apache.org/tomcat/tomcat-9/v9.0.85/bin/apache-tomcat-9.0.85.tar.gz 
    dest: /opt
- name: extract
  unarchive:
    src: /opt
    dest: /opt
    remote_src: yes

- name: create deamon
  get_url:
    src: https://s3-us-west-2.amazonaws.com/studentapi-cit/tomcat-init
    dest: /etc/init.d/tomcatd
  notify: start tomcat

- name: deploy war
  get_url:
    src: https://s3-us-west-2.amazonaws.com/studentapi-cit/student.war
    dest: /opt/apache-tomcat-9.0.85/webapps/