---
# tasks file for database_connect
- name: mysql connector
  become: true
  get_url:
    url: https://s3-us-west-2.amazonaws.com/studentapi-cit/mysql-connector.jar
    dest: /opt/

- name: Copy a file into the container
  community.docker.docker_container_copy_into:
    container: register-app
    path: /opt/mysql-connector.jar
    container_path: /usr/local/tomcat/lib/
- name: copy context.xml
  become: true
  copy: 
    src: context.xml
    dest: /opt/  
- name: reload a container
  community.docker.docker_container:
    name: register-app
    image: httpd
    state: started
    restart: true  
- name: Copy a file into the container
  become: true
  community.docker.docker_container_copy_into:
    container: register-app
    path: /opt/context.xml
    container_path: /usr/local/tomcat/conf/context.xml
